### ISSUE TITLE
Error while importing products 

### ISSUE THREAD

**Issue by dtwpt** [IcecatNV/Icecat-Integration#11]
Bundle 3.0
Pimcore Platform (v10.5.12|a067c313fed7ff36707df37c0458934473a65667)

`[2022-12-14T20:29:34.082713+00:00] clientobjectcreate.ERROR: ERROR IN  OBJECT CREATION FOR JOB ID :639a321b72918 AND PRODUCT ID :101286924-Call to undefined method Pimcore\Model\DataObject\Classificationstore\KeyConfig::setCacheEnabled() {"detail":"#0 /var/www/html/3bpim/vendor/icecat/icecat-integration/src/Services/CreateObjectService.php(1210): IceCatBundle\\Services\\CreateObjectService->createStoreKey()\n#1 /var/www/html/3bpim/vendor/icecat/icecat-integration/src/Services/CreateObjectService.php(317): IceCatBundle\\Services\\CreateObjectService->createDynamicFields()\n#2 /var/www/html/3bpim/vendor/icecat/icecat-integration/src/Services/CreateObjectService.php(222): IceCatBundle\\Services\\CreateObjectService->createIceCatObject()\n#3 /var/www/html/3bpim/vendor/icecat/icecat-integration/src/Command/IceCatCreateObjectCommand.php(33): IceCatBundle\\Services\\CreateObjectService->createObject()\n#4 /var/www/html/3bpim/vendor/symfony/console/Command/Command.php(298): IceCatBundle\\Command\\IceCatCreateObjectCommand->execute()\n#5 /var/www/html/3bpim/vendor/symfony/console/Application.php(1058): Symfony\\Component\\Console\\Command\\Command->run()\n#6 /var/www/html/3bpim/vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\\Component\\Console\\Application->doRunCommand()\n#7 /var/www/html/3bpim/vendor/symfony/console/Application.php(301): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRunCommand()\n#8 /var/www/html/3bpim/vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\\Component\\Console\\Application->doRun()\n#9 /var/www/html/3bpim/vendor/symfony/console/Application.php(171): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRun()\n#10 /var/www/html/3bpim/bin/console(48): Symfony\\Component\\Console\\Application->run()\n#11 {main}"} []
[2022-12-14T20:29:35.974537+00:00] clientobjectcreate.ERROR: ERROR IN  OBJECT CREATION FOR JOB ID :639a321b72918 AND PRODUCT ID :101286924-Call to undefined method Pimcore\Model\DataObject\Classificationstore\KeyConfig::setCacheEnabled() {"detail":"#0 /var/www/html/3bpim/vendor/icecat/icecat-integration/src/Services/CreateObjectService.php(1210): IceCatBundle\\Services\\CreateObjectService->createStoreKey()\n#1 /var/www/html/3bpim/vendor/icecat/icecat-integration/src/Services/CreateObjectService.php(317): IceCatBundle\\Services\\CreateObjectService->createDynamicFields()\n#2 /var/www/html/3bpim/vendor/icecat/icecat-integration/src/Services/CreateObjectService.php(222): IceCatBundle\\Services\\CreateObjectService->createIceCatObject()\n#3 /var/www/html/3bpim/vendor/icecat/icecat-integration/src/Command/IceCatCreateObjectCommand.php(33): IceCatBundle\\Services\\CreateObjectService->createObject()\n#4 /var/www/html/3bpim/vendor/symfony/console/Command/Command.php(298): IceCatBundle\\Command\\IceCatCreateObjectCommand->execute()\n#5 /var/www/html/3bpim/vendor/symfony/console/Application.php(1058): Symfony\\Component\\Console\\Command\\Command->run()\n#6 /var/www/html/3bpim/vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\\Component\\Console\\Application->doRunCommand()\n#7 /var/www/html/3bpim/vendor/symfony/console/Application.php(301): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRunCommand()\n#8 /var/www/html/3bpim/vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\\Component\\Console\\Application->doRun()\n#9 /var/www/html/3bpim/vendor/symfony/console/Application.php(171): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRun()\n#10 /var/www/html/3bpim/bin/console(48): Symfony\\Component\\Console\\Application->run()\n#11 {main}"} []
[`

**Comment by IcecatNV** [comment]
Hi Miguel,  We have tested the 3.0.0 bundle on Pimcore version 10.2.x. And since you are using Pimcore 10.5.x, there could be compatibility issues.

**Comment by dtwpt** [comment]
i've since them fixed the code, and created the Database manually and its working so far.

**Comment by IcecatNV** [comment]
Hi @dtwpt 

We have fixed the above issue by making the plugin compatible with the Pimcore version 10.5.* and released a new V4.0.0 version. 

Please test and confirm once the issue has been resolved at your end so that then I will close this issue.
